-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.coupon_usage (
  id integer NOT NULL DEFAULT nextval('coupon_usage_id_seq'::regclass),
  coupon_id integer,
  customer_id integer,
  job_id integer,
  invoice_id integer,
  used_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  discount_amount numeric NOT NULL,
  CONSTRAINT coupon_usage_pkey PRIMARY KEY (id),
  CONSTRAINT coupon_usage_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES public.coupons(id),
  CONSTRAINT coupon_usage_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT coupon_usage_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT coupon_usage_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.coupons (
  id integer NOT NULL DEFAULT nextval('coupons_id_seq'::regclass),
  user_id integer,
  code character varying NOT NULL UNIQUE,
  discount_type USER-DEFINED NOT NULL,
  discount_amount numeric NOT NULL,
  application_type USER-DEFINED DEFAULT 'all'::application_type,
  selected_services jsonb,
  doesnt_expire boolean DEFAULT false,
  expiration_date date,
  restrict_before_expiration boolean DEFAULT false,
  limit_total_uses boolean DEFAULT false,
  total_uses_limit integer,
  current_uses integer DEFAULT 0,
  can_combine_with_recurring boolean DEFAULT false,
  recurring_application_type USER-DEFINED DEFAULT 'all'::recurring_application_type,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT coupons_pkey PRIMARY KEY (id),
  CONSTRAINT coupons_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.custom_payment_methods (
  id integer NOT NULL DEFAULT nextval('custom_payment_methods_id_seq'::regclass),
  user_id integer,
  name character varying NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT custom_payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT custom_payment_methods_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.customer_notification_preferences (
  id integer NOT NULL DEFAULT nextval('customer_notification_preferences_id_seq'::regclass),
  customer_id integer UNIQUE,
  email_notifications boolean DEFAULT false,
  sms_notifications boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT customer_notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT customer_notification_preferences_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.customer_notifications (
  id integer NOT NULL DEFAULT nextval('customer_notifications_id_seq'::regclass),
  customer_id integer,
  job_id integer,
  type USER-DEFINED NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::notification_status,
  sent_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT customer_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT customer_notifications_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_notifications_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.customers (
  id integer NOT NULL DEFAULT nextval('customers_id_seq'::regclass),
  user_id integer,
  first_name character varying NOT NULL,
  last_name character varying,
  email character varying,
  phone character varying,
  address text,
  suite character varying,
  city character varying,
  state character varying,
  zip_code character varying,
  notes text,
  status USER-DEFINED DEFAULT 'active'::user_status,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.estimates (
  id integer NOT NULL DEFAULT nextval('estimates_id_seq'::regclass),
  user_id integer,
  customer_id integer,
  services jsonb,
  total_amount numeric NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::estimate_status,
  valid_until date,
  notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT estimates_pkey PRIMARY KEY (id),
  CONSTRAINT estimates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT estimates_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.invoices (
  id integer NOT NULL DEFAULT nextval('invoices_id_seq'::regclass),
  user_id integer NOT NULL,
  customer_id integer,
  job_id integer,
  estimate_id integer,
  amount numeric NOT NULL,
  tax_amount numeric DEFAULT 0.00,
  total_amount numeric NOT NULL,
  status USER-DEFINED DEFAULT 'draft'::invoice_status,
  due_date date,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT invoices_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.job_answers (
  id integer NOT NULL DEFAULT nextval('job_answers_id_seq'::regclass),
  job_id integer,
  question_id character varying NOT NULL,
  question_text text NOT NULL,
  question_type character varying NOT NULL,
  answer text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT job_answers_pkey PRIMARY KEY (id),
  CONSTRAINT job_answers_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.job_offers (
  id integer NOT NULL DEFAULT nextval('job_offers_id_seq'::regclass),
  job_id integer NOT NULL,
  team_member_id integer NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  claimed_at timestamp without time zone,
  responded_at timestamp without time zone,
  notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT job_offers_pkey PRIMARY KEY (id),
  CONSTRAINT job_offers_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_offers_team_member_id_fkey FOREIGN KEY (team_member_id) REFERENCES public.team_members(id)
);
CREATE TABLE public.job_status_history (
  id integer NOT NULL DEFAULT nextval('job_status_history_id_seq'::regclass),
  job_id integer NOT NULL,
  status character varying NOT NULL,
  previous_status character varying,
  changed_by character varying,
  changed_by_type character varying DEFAULT 'account_owner'::character varying,
  changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT job_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT job_status_history_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.job_team_assignments (
  id integer NOT NULL DEFAULT nextval('job_team_assignments_id_seq'::regclass),
  job_id integer,
  team_member_id integer,
  is_primary boolean DEFAULT false,
  assigned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  assigned_by integer,
  CONSTRAINT job_team_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT job_team_assignments_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_team_assignments_team_member_id_fkey FOREIGN KEY (team_member_id) REFERENCES public.team_members(id),
  CONSTRAINT job_team_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id)
);
CREATE TABLE public.job_templates (
  id integer NOT NULL DEFAULT nextval('job_templates_id_seq'::regclass),
  user_id integer,
  name character varying NOT NULL,
  description text,
  service_id integer,
  estimated_duration integer,
  estimated_price numeric,
  default_notes text,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT job_templates_pkey PRIMARY KEY (id),
  CONSTRAINT job_templates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT job_templates_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.jobs (
  id integer NOT NULL DEFAULT nextval('jobs_id_seq'::regclass),
  user_id integer,
  customer_id integer,
  service_id integer,
  team_member_id integer,
  territory_id integer,
  notes text,
  status USER-DEFINED,
  invoice_status character varying,
  invoice_id integer,
  invoice_amount numeric,
  invoice_date date,
  payment_date date,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  is_recurring boolean DEFAULT false,
  recurring_frequency character varying,
  next_billing_date date,
  stripe_payment_intent_id character varying,
  duration integer DEFAULT 360,
  workers integer DEFAULT 1,
  skills_required integer DEFAULT 0,
  price numeric DEFAULT 0.00,
  discount numeric DEFAULT 0.00,
  additional_fees numeric DEFAULT 0.00,
  taxes numeric DEFAULT 0.00,
  total numeric DEFAULT 0.00,
  payment_method character varying,
  territory character varying,
  schedule_type character varying,
  let_customer_schedule boolean DEFAULT false,
  offer_to_providers boolean DEFAULT false,
  internal_notes text,
  contact_info jsonb,
  customer_notes text,
  scheduled_time time without time zone DEFAULT '09:00:00'::time without time zone,
  service_address_street character varying,
  service_address_city character varying,
  service_address_state character varying,
  service_address_zip character varying,
  service_address_country character varying DEFAULT 'USA'::character varying,
  service_address_lat numeric,
  service_address_lng numeric,
  service_name character varying,
  bathroom_count character varying,
  workers_needed integer DEFAULT 1,
  skills jsonb,
  service_price numeric DEFAULT 0.00,
  total_amount numeric DEFAULT 0.00,
  estimated_duration integer,
  special_instructions text,
  payment_status character varying,
  priority character varying,
  quality_check boolean DEFAULT true,
  photos_required boolean DEFAULT false,
  customer_signature boolean DEFAULT false,
  auto_invoice boolean DEFAULT true,
  auto_reminders boolean DEFAULT true,
  recurring_end_date date,
  tags jsonb,
  intake_question_answers jsonb,
  service_modifiers jsonb,
  service_intake_questions jsonb,
  scheduled_date text NOT NULL,
  confirmation_sent boolean DEFAULT false,
  confirmation_sent_at timestamp without time zone,
  confirmation_email character varying,
  confirmation_failed boolean DEFAULT false,
  confirmation_error text,
  confirmation_no_email boolean DEFAULT false,
  reminder_sent boolean DEFAULT false,
  reminder_sent_at timestamp without time zone,
  reminder_email character varying,
  reminder_failed boolean DEFAULT false,
  reminder_error text,
  reminder_no_email boolean DEFAULT false,
  sms_sent boolean DEFAULT false,
  sms_sent_at timestamp without time zone,
  sms_phone character varying,
  sms_sid character varying,
  sms_failed boolean DEFAULT false,
  sms_error text,
  start_time timestamp without time zone,
  end_time timestamp without time zone,
  hours_worked numeric,
  google_calendar_event_id character varying,
  google_calendar_event_link text,
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT jobs_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT jobs_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT jobs_team_member_id_fkey FOREIGN KEY (team_member_id) REFERENCES public.team_members(id),
  CONSTRAINT jobs_territory_id_fkey FOREIGN KEY (territory_id) REFERENCES public.territories(id)
);
CREATE TABLE public.lead_pipelines (
  id integer NOT NULL DEFAULT nextval('lead_pipelines_id_seq'::regclass),
  user_id integer NOT NULL,
  name character varying NOT NULL DEFAULT 'Default Pipeline'::character varying,
  is_default boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT lead_pipelines_pkey PRIMARY KEY (id),
  CONSTRAINT lead_pipelines_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.lead_stages (
  id integer NOT NULL DEFAULT nextval('lead_stages_id_seq'::regclass),
  pipeline_id integer NOT NULL,
  name character varying NOT NULL,
  color character varying DEFAULT '#3B82F6'::character varying,
  position integer NOT NULL DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT lead_stages_pkey PRIMARY KEY (id),
  CONSTRAINT lead_stages_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES public.lead_pipelines(id)
);
CREATE TABLE public.lead_tasks (
  id integer NOT NULL DEFAULT nextval('lead_tasks_id_seq'::regclass),
  lead_id integer NOT NULL,
  user_id integer NOT NULL,
  title character varying NOT NULL,
  description text,
  due_date timestamp without time zone,
  status character varying DEFAULT 'pending'::character varying,
  priority character varying DEFAULT 'medium'::character varying,
  assigned_to integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  completed_at timestamp without time zone,
  CONSTRAINT lead_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT lead_tasks_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT lead_tasks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT lead_tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.team_members(id)
);
CREATE TABLE public.leads (
  id integer NOT NULL DEFAULT nextval('leads_id_seq'::regclass),
  user_id integer NOT NULL,
  pipeline_id integer NOT NULL,
  stage_id integer NOT NULL,
  first_name character varying,
  last_name character varying,
  email character varying,
  phone character varying,
  company character varying,
  source character varying,
  notes text,
  value numeric,
  converted_customer_id integer,
  converted_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT leads_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES public.lead_pipelines(id),
  CONSTRAINT leads_stage_id_fkey FOREIGN KEY (stage_id) REFERENCES public.lead_stages(id),
  CONSTRAINT leads_converted_customer_id_fkey FOREIGN KEY (converted_customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.notification_templates (
  id integer NOT NULL DEFAULT nextval('notification_templates_id_seq'::regclass),
  user_id integer,
  name character varying NOT NULL,
  type USER-DEFINED NOT NULL,
  subject character varying,
  message text NOT NULL,
  variables jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notification_templates_pkey PRIMARY KEY (id),
  CONSTRAINT notification_templates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.requests (
  id integer NOT NULL DEFAULT nextval('requests_id_seq'::regclass),
  user_id integer,
  customer_id integer,
  customer_name character varying,
  customer_email character varying,
  service_id integer,
  type USER-DEFINED NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::request_status,
  scheduled_date date,
  scheduled_time time without time zone,
  estimated_duration character varying,
  estimated_price numeric,
  notes text,
  rejection_reason text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT requests_pkey PRIMARY KEY (id),
  CONSTRAINT requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT requests_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT requests_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.service_availability (
  id integer NOT NULL DEFAULT nextval('service_availability_id_seq'::regclass),
  service_id integer,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_available boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT service_availability_pkey PRIMARY KEY (id),
  CONSTRAINT service_availability_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.service_categories (
  id integer NOT NULL DEFAULT nextval('service_categories_id_seq'::regclass),
  user_id integer,
  name character varying NOT NULL,
  description text,
  color character varying DEFAULT '#3B82F6'::character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT service_categories_pkey PRIMARY KEY (id),
  CONSTRAINT service_categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.service_flow (
  id integer NOT NULL DEFAULT nextval('service_flow_id_seq'::regclass),
  user_id integer UNIQUE,
  settings jsonb NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT service_flow_pkey PRIMARY KEY (id),
  CONSTRAINT service_flow_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.service_scheduling_rules (
  id integer NOT NULL DEFAULT nextval('service_scheduling_rules_id_seq'::regclass),
  service_id integer,
  rule_type character varying NOT NULL,
  rule_value jsonb NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT service_scheduling_rules_pkey PRIMARY KEY (id),
  CONSTRAINT service_scheduling_rules_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.service_timeslot_templates (
  id integer NOT NULL DEFAULT nextval('service_timeslot_templates_id_seq'::regclass),
  user_id integer,
  name character varying NOT NULL,
  time_slots jsonb NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT service_timeslot_templates_pkey PRIMARY KEY (id),
  CONSTRAINT service_timeslot_templates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.services (
  id integer NOT NULL DEFAULT nextval('services_id_seq'::regclass),
  user_id integer,
  name character varying NOT NULL,
  description text,
  price numeric,
  duration integer,
  category character varying,
  image character varying,
  modifiers jsonb,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  require_payment_method boolean DEFAULT false,
  is_active boolean DEFAULT true,
  intake_questions jsonb,
  category_id integer,
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT services_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.team_member_job_assignments (
  id integer NOT NULL DEFAULT nextval('team_member_job_assignments_id_seq'::regclass),
  job_id integer,
  team_member_id integer,
  is_primary boolean DEFAULT false,
  assigned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  assigned_by integer,
  CONSTRAINT team_member_job_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT team_member_job_assignments_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT team_member_job_assignments_team_member_id_fkey FOREIGN KEY (team_member_id) REFERENCES public.team_members(id),
  CONSTRAINT team_member_job_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id)
);
CREATE TABLE public.team_member_notifications (
  id integer NOT NULL DEFAULT nextval('team_member_notifications_id_seq'::regclass),
  team_member_id integer,
  type USER-DEFINED NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::notification_status,
  sent_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT team_member_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT team_member_notifications_team_member_id_fkey FOREIGN KEY (team_member_id) REFERENCES public.team_members(id)
);
CREATE TABLE public.team_member_sessions (
  id integer NOT NULL DEFAULT nextval('team_member_sessions_id_seq'::regclass),
  team_member_id integer,
  session_token character varying NOT NULL UNIQUE,
  expires_at timestamp without time zone NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT team_member_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT team_member_sessions_team_member_id_fkey FOREIGN KEY (team_member_id) REFERENCES public.team_members(id)
);
CREATE TABLE public.team_members (
  id integer NOT NULL DEFAULT nextval('team_members_id_seq'::regclass),
  user_id integer,
  first_name character varying,
  last_name character varying,
  email character varying NOT NULL,
  phone character varying,
  role character varying,
  username character varying UNIQUE,
  password character varying,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  verification_token character varying,
  reset_token character varying,
  reset_token_expires timestamp without time zone,
  last_login timestamp without time zone,
  skills jsonb,
  hourly_rate numeric,
  availability jsonb,
  profile_picture character varying,
  status USER-DEFINED DEFAULT 'active'::team_member_status,
  permissions jsonb,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  location character varying,
  city character varying,
  state character varying,
  zip_code character varying,
  is_service_provider boolean DEFAULT true,
  territories jsonb,
  invitation_token character varying,
  invitation_expires timestamp without time zone,
  settings jsonb,
  color character varying DEFAULT '#2563EB'::character varying,
  commission_percentage numeric,
  CONSTRAINT team_members_pkey PRIMARY KEY (id),
  CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.territories (
  id integer NOT NULL DEFAULT nextval('territories_id_seq'::regclass),
  user_id integer,
  name character varying NOT NULL,
  description text,
  zip_codes jsonb,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  location character varying,
  radius_miles numeric DEFAULT 25.00,
  timezone character varying DEFAULT 'America/New_York'::character varying,
  status USER-DEFINED DEFAULT 'active'::territory_status,
  business_hours jsonb,
  team_members jsonb,
  services jsonb,
  pricing_multiplier numeric DEFAULT 1.00,
  CONSTRAINT territories_pkey PRIMARY KEY (id),
  CONSTRAINT territories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.territory_pricing (
  id integer NOT NULL DEFAULT nextval('territory_pricing_id_seq'::regclass),
  territory_id integer,
  service_id integer,
  base_price numeric NOT NULL,
  multiplier numeric DEFAULT 1.00,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT territory_pricing_pkey PRIMARY KEY (id),
  CONSTRAINT territory_pricing_territory_id_fkey FOREIGN KEY (territory_id) REFERENCES public.territories(id),
  CONSTRAINT territory_pricing_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.transactions (
  id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass),
  user_id integer NOT NULL,
  invoice_id integer NOT NULL,
  customer_id integer,
  job_id integer,
  amount numeric NOT NULL,
  payment_intent_id character varying NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  payment_method character varying NOT NULL DEFAULT 'card'::character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT transactions_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT transactions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT transactions_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.user_availability (
  id integer NOT NULL DEFAULT nextval('user_availability_id_seq'::regclass),
  user_id integer,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_available boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  business_hours jsonb,
  timeslot_templates jsonb,
  CONSTRAINT user_availability_pkey PRIMARY KEY (id),
  CONSTRAINT user_availability_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_billing (
  id integer NOT NULL DEFAULT nextval('user_billing_id_seq'::regclass),
  user_id integer NOT NULL UNIQUE,
  stripe_customer_id character varying,
  stripe_subscription_id character varying,
  plan_type character varying,
  billing_cycle character varying,
  next_billing_date date,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  stripe_publishable_key character varying,
  stripe_secret_key character varying,
  CONSTRAINT user_billing_pkey PRIMARY KEY (id),
  CONSTRAINT user_billing_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_user_billing_user_id FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_branding (
  id integer NOT NULL DEFAULT nextval('user_branding_id_seq'::regclass),
  user_id integer UNIQUE,
  logo_url character varying,
  primary_color character varying DEFAULT '#3B82F6'::character varying,
  secondary_color character varying,
  font_family character varying,
  custom_css text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_branding_pkey PRIMARY KEY (id),
  CONSTRAINT user_branding_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_notification_settings (
  id integer NOT NULL DEFAULT nextval('user_notification_settings_id_seq'::regclass),
  user_id integer UNIQUE,
  email_notifications boolean DEFAULT true,
  sms_notifications boolean DEFAULT false,
  push_notifications boolean DEFAULT true,
  notification_types jsonb,
  quiet_hours_start time without time zone,
  quiet_hours_end time without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_notification_settings_pkey PRIMARY KEY (id),
  CONSTRAINT user_notification_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_payment_settings (
  id integer NOT NULL DEFAULT nextval('user_payment_settings_id_seq'::regclass),
  user_id integer UNIQUE,
  stripe_account_id character varying,
  stripe_publishable_key character varying,
  stripe_secret_key character varying,
  payment_methods jsonb,
  auto_invoice boolean DEFAULT true,
  invoice_reminders boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_payment_settings_pkey PRIMARY KEY (id),
  CONSTRAINT user_payment_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_service_areas (
  id integer NOT NULL DEFAULT nextval('user_service_areas_id_seq'::regclass),
  user_id integer,
  name character varying NOT NULL,
  zip_codes jsonb,
  radius_miles numeric DEFAULT 25.00,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_service_areas_pkey PRIMARY KEY (id),
  CONSTRAINT user_service_areas_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  email character varying NOT NULL UNIQUE,
  password character varying NOT NULL,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  business_name character varying,
  business_email character varying,
  phone character varying,
  email_notifications boolean DEFAULT true,
  sms_notifications boolean DEFAULT false,
  profile_picture character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  is_active boolean DEFAULT true,
  business_slug character varying UNIQUE,
  google_id text,
  twilio_connect_account_sid text,
  twilio_connect_status character varying,
  twilio_phone_number character varying,
  stripe_connect_account_id text,
  stripe_connect_access_token text,
  stripe_connect_status character varying,
  twilio_account_sid character varying,
  twilio_auth_token character varying,
  twilio_notification_phone character varying,
  twilio_notification_types jsonb,
  staff_locations_enabled boolean DEFAULT true,
  google_calendar_enabled boolean DEFAULT false,
  google_calendar_id character varying DEFAULT 'primary'::character varying,
  google_access_token text,
  google_refresh_token text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);